### ISSUE TITLE
pdf2hashcat.py stops prematurely at `\)` in literal string

### ISSUE THREAD

**Issue by JDLH** [stricture/hashstack-server-plugin-hashcat#11]
Function **get_passwords_for_JtR()** intends to parse literal, parenthesis-delimited PDF string values for names /U, /O, /UE, /OE. Literal strings may include an escaped right parenthesis, e.g. `(\))`. In this case, the function terminates the string just before the `\)`, and returns a truncated string.

**To reproduce**
Simple test case: Parse a string like `"""/U(ab\)c(d)e)"""` .
Actual data from a PDF file: `…"""/U(:\x00\xafe\x16q\xd3\)r\xc4\xac\xf6\x80\xd6\xfc\xe6\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00)"""` .

**Observed behaviour**
Simple case: `pas` is `"""/U (ab\)"""` .
Actual case: `pas` is `"""/U(:\x00\xafe\x16q\xd3\)"""` .

**Expected behaviour**
Simple case: `pas` is `"""/U (ab\)c(d)e)"""` .
Actual case: `pas` is `"""/U(:\x00\xafe\x16q\xd3\)r\xc4\xac\xf6\x80\xd6\xfc\xe6\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00)"""` .

**Discussion**
The test at [L129](https://github.com/stricture/hashstack-server-plugin-hashcat/blob/12fc138d2864026765f55bb33e3d7b859eb2b48a/scrapers/pdf2hashcat.py#L129) reads, `(pas[-2] == b'\\')` .  This fails on Python 3 interpreters, where **bytes** is an array of integers, not bytes.  This module has code for this difference elsewhere.  The condition in L129 should perhaps be changed to read, `(pas[-2] == (b'\\'[0] if not PY3 else b'\\'))` .

Be careful in interpreting the output of Python print statements. Python will double a single backslash. It is important to undo that in one's mind when reading the output.  I undid the doubling in the reproduction and behaviour code above.

**Comment by JDLH** [comment]
I believe the comment in [L128](https://github.com/stricture/hashstack-server-plugin-hashcat/blob/12fc138d2864026765f55bb33e3d7b859eb2b48a/scrapers/pdf2hashcat.py#L128) is incorrect. It is not that "regexs in python suck <=== LOL". The fundamental problem with that function is that it attempts to parse PDF string literals, a context-free but not regular language, using the tools of regular languages. 

To parse the nested parentheses of PDF string literals correctly, the code would have to increment a count for each opening parenthesis it parsed, and decrement the count for each balanced closing parenthesis. 

This code also looks fragile in the face of other trivial syntax variations. For instance, if there is space between the name and the literal string (e.g. `"""/UE (abc)"""`, then I suspect function **get_password_from_byte_string()** would exclude the `"""/UE """`, but include the hex code for the opening parenthesis in the output.

Overall the robust way to write a utility like this is to let a robust PDF parsing library like [pypdf](https://pypdf.readthedocs.io/en/stable/index.html) read the syntax, and just call that library to retrieve the binary values needed for the hash.

**Comment by epixoip** [comment]
You've opened an issue for an 11 year old script that was last modified 9 years ago, residing in a repository that hasn't been updated in 8 years, that was part of a software package that reached EOL 6 years ago, belonging to a company that went out of business 4 years ago. 

If you're looking for the latest version of this script, see https://github.com/openwall/john/blob/bleeding-jumbo/run/pdf2john.py
