### ISSUE TITLE
Office2Hashcat.py AttributeError: 'ElementTree' object has no attribute 'getiterator'

### ISSUE THREAD

**Issue by infosecconsultant** [stricture/hashstack-server-plugin-hashcat#5]
The error occurs when the script is used in python3.9+ because the code xml.etree.ElementTree.Element.getiterator() which had been deprecated with a warning previously, has now been removed.

Other people have suggested a workaround is to install another engine openpyxl to read the excel file. Unsure if it'll work in this instance.

**Comment by dbrown8050** [comment]
Getting the same error.  Is there a new version of office2hashcat? The version I have is .42 from 2015-01-25

**Comment by DDvO** [comment]
The obvious workaround is to use an earlier version of Python.

I just successfully used
```
python2.7 office2hashcat.py test.docx >hash.txt
```

**Comment by epixoip** [comment]
use https://github.com/openwall/john/blob/bleeding-jumbo/run/office2john.py
