### ISSUE TITLE
pdf2hashcat.py wraps hash in spurious b'...'

### ISSUE THREAD

**Issue by JDLH** [stricture/hashstack-server-plugin-hashcat#9]
When one runs `pdf2hashcat.py`, the resulting hash should be something like (with the middle of the hash elided for brevity):
```
$pdf$5*6*256*-3392*1*…bb9a
```
but instead it is:
```
b'$pdf$5*6*256*-3392*1*…bb9a'
```

The beginning `b'` and ending `'` are a result of a Python usage error. They are not part of the hash. If they are present, then **hashcat** rejects the hash with an error message, "Signature unmatched".

The fix is to change [line 115 of `pdf2hashcat.py`](https://github.com/stricture/hashstack-server-plugin-hashcat/blob/12fc138d2864026765f55bb33e3d7b859eb2b48a/scrapers/pdf2hashcat.py#L115) from:
```
        sys.stdout.write("%s\n" % output.encode('UTF-8'))
``` 
to:
```
        sys.stdout.write(output+"\n")
```
.

**Discussion**: `sys.stdout` is a "regular [text file[]](https://docs.python.org/3/glossary.html#term-text-file) like those returned by the [open()](https://docs.python.org/3/library/functions.html#open) function." Thus, the program should write text `str` objects, rather than `bytes` such as those returned by `str.encode()` . The spurious `b'`…`'` are what Python prints when you write a `bytes` object to a text file. The encoding of `sys.stdout` is system-dependent, but it should not matter, because the hash is ASCII-compatible anyway.

Bug reproduced, and fix tested, on Python 3.9 on macOS Monterey 12.7.4.

**Comment by epixoip** [comment]
See comments on other issue.
